/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://pjkeze2srfcxpafayfo57icc5e.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jodqepo4ereg5puao3yc2uohd4",
    "aws_cognito_identity_pool_id": "us-west-1:7ff75d78-1bec-48ec-a18b-098c85b0dc25",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_HarbyY9nK",
    "aws_user_pools_web_client_id": "33dmeq197qaqmgj5ige75mvqed",
    "oauth": {
        "domain": "shamefully-staging.auth.us-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://www.shameful.ly/",
        "redirectSignOut": "http://localhost:3000/,https://www.shameful.ly/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_mobile_analytics_app_id": "e67493508dc649cf8d5b126921c73afb",
    "aws_mobile_analytics_app_region": "us-west-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "e67493508dc649cf8d5b126921c73afb",
            "region": "us-west-2"
        }
    },
    "Notifications": {
        "SMS": {
            "AWSPinpoint": {
                "appId": "e67493508dc649cf8d5b126921c73afb",
                "region": "us-west-2"
            }
        }
    },
    "aws_user_files_s3_bucket": "shamefully1120300-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
